#                                                              -*- Makefile -*-
# Simics module makefile
#

MODULE_COMPONENTS := RISC_controller

PYTHON_FILES = myrisc_comp.py module_load.py

THREAD_SAFE=yes
SIMICS_API := latest

include $(MODULE_MAKEFILE)
