#                                                              -*- Makefile -*-
# Simics module makefile
#

MODULE_COMPONENTS := sample_pci_card

SIMICS_API := latest
THREAD_SAFE:=yes
PYTHON_FILES = sample_components.py module_load.py

include $(MODULE_MAKEFILE)
