#                                                              -*- Makefile -*-
# Simics module makefile
#

MODULE_CLASSES = mem_mng

SRC_FILES = mem-mng.dml

PYTHON_FILES = module_load.py

SIMICS_API := 6
THREAD_SAFE:= yes

include $(MODULE_MAKEFILE)

